baseURL = 'https://ghariib.ir/'
languageCode = 'en-us'
title = 'Gharib Personal Blog'
theme = 'smol'
copyright = 'Alireza Gharib. All right reserved'
ignoreLogs = ['warning-goldmark-raw-html']
# Parameters
[params]
    subtitle = "A Techi Personal Blog"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/Gharib110"
        weight = 1 
